// <auto-generated />
using System;
using FinanceTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceTracker.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceTracker.Entities.BaseAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BaseAccounts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseAccount");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FinanceTracker.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("BaseAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BaseAccountId");

                    b.ToTable("Transactions");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FinanceTracker.Entities.CreditCardAccount", b =>
                {
                    b.HasBaseType("FinanceTracker.Entities.BaseAccount");

                    b.HasDiscriminator().HasValue("CreditCardAccount");
                });

            modelBuilder.Entity("FinanceTracker.Entities.SavingsAccount", b =>
                {
                    b.HasBaseType("FinanceTracker.Entities.BaseAccount");

                    b.HasDiscriminator().HasValue("SavingsAccount");
                });

            modelBuilder.Entity("FinanceTracker.Entities.ExpenseTransaction", b =>
                {
                    b.HasBaseType("FinanceTracker.Entities.Transaction");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FinanceTracker.Entities.IncomeTransaction", b =>
                {
                    b.HasBaseType("FinanceTracker.Entities.Transaction");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("FinanceTracker.Entities.TransferTransaction", b =>
                {
                    b.HasBaseType("FinanceTracker.Entities.Transaction");

                    b.Property<int>("ToAccountId")
                        .HasColumnType("int");

                    b.HasIndex("ToAccountId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("FinanceTracker.Entities.BaseAccount", b =>
                {
                    b.OwnsOne("FinanceTracker.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<int>("BaseAccountId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BalanceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BalanceCurrency");

                            b1.HasKey("BaseAccountId");

                            b1.ToTable("BaseAccounts");

                            b1.WithOwner()
                                .HasForeignKey("BaseAccountId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceTracker.Entities.Transaction", b =>
                {
                    b.HasOne("FinanceTracker.Entities.BaseAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanceTracker.Entities.BaseAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("BaseAccountId");

                    b.OwnsOne("FinanceTracker.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BalanceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("BalanceCurrency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("FinanceTracker.ValueObjects.Category", "Category", b1 =>
                        {
                            b1.Property<int>("TransactionId")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CategoryDescription");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CategoryName");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CategoryType");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Category")
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceTracker.Entities.CreditCardAccount", b =>
                {
                    b.OwnsOne("FinanceTracker.ValueObjects.Money", "CreditLimit", b1 =>
                        {
                            b1.Property<int>("CreditCardAccountId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CreditLimitAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CreditLimitCurrency");

                            b1.HasKey("CreditCardAccountId");

                            b1.ToTable("BaseAccounts");

                            b1.WithOwner()
                                .HasForeignKey("CreditCardAccountId");
                        });

                    b.Navigation("CreditLimit")
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceTracker.Entities.TransferTransaction", b =>
                {
                    b.HasOne("FinanceTracker.Entities.BaseAccount", "ToAccount")
                        .WithMany()
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ToAccount");
                });

            modelBuilder.Entity("FinanceTracker.Entities.BaseAccount", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
