services:
  finance-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: finance-api-container
    ports:
      - "5090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_PASSWORD}
      - JwtSettings__Key=${JWT_KEY}

  finance-ui:
    build:
      context: .
      dockerfile: UI/Dockerfile
    container_name: finance-ui-container
    ports:
      - "5027:80"
    depends_on:
      - finance-api